name: IaC Scanning

on:
  push:
    branches:
      - main
      - "feature/**"
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  checkov-terraform:
    name: Scan Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Checkov (report, non-blocking)
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: infra/terraform
          framework: terraform
          output_format: sarif
          soft_fail: true

      - name: Upload Terraform Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkov-terraform-report
          path: checkov-terraform-report.json

      

  checkov-kubernetes:
    name: Scan Kubernetes Manifests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Checkov (report, non-blocking)
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: infra/kubernetes
          framework: kubernetes
          output_format: json
          output_file_path: checkov-k8s-report.json
          soft_fail: true

      - name: Upload Kubernetes Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkov-k8s-report
          path: checkov-k8s-report.json

      